steps:
# Docker build
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build', 
          '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:latest', 
          '--cache-from', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:latest',
          '.'
        ]
  timeout: 500s

# Save docker image to Container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:latest']

# Deploy to App Engine
- name: "gcr.io/cloud-builders/gcloud"
  args: [
          "app", "deploy", "deploy/app.yaml", 
          "--image-url=gcr.io/$PROJECT_ID/$BRANCH_NAME:latest"
        ]